function fig = buildModelManager()
%
% Builder for the ModelManager View
%

% import tree package
import uiextras.jTree.*

% Make the figure
fig = figure('Name','Model Manager','NumberTitle','off',...
    'MenuBar','none','ToolBar','none','Units','normalized',...
    'Position',[0.76 0.1 0.22 0.78],'Visible','off','Tag','fig');

% Add grid & box for panels
grid = uix.Grid( 'Parent', fig, 'Spacing', 0); 
box = uix.VBox( 'Parent', grid,'Padding',5,'Spacing',4, 'Tag', 'box');

% Add processing mode panel, file selection panel & process selection panel
mode_panel = uix.Panel( 'Parent', box,...
                        'Title', 'Fitting Mode',...
                        'Padding',2);
file_panel = uix.Panel( 'Parent', box,...
            'Title', 'File selection',...
            'Padding',2);
process_panel = uix.Panel( 'Parent', box,...
                           'Title', 'Model settings',...
                           'Padding',2);                       
result_panel = uix.Panel( 'Parent', box,...
                           'Title', 'Model results',...
                           'Padding',2);
                       
% Add RunButton
buttonbox = uix.HButtonBox( 'Parent', box,...
                            'Spacing', 15,...
                            'HorizontalAlignment','center',...
                            'ButtonSize', [200 40] ); 
                        
uicontrol( 'Parent', buttonbox,...
            'Style','pushbutton',...
            'String','Run Fit',...
            'Tag','RunPushButton'); 
                        
% Mode Panel
% + Radio button
buttonbox = uix.HButtonBox( 'Parent', mode_panel,...
                            'Spacing', 15,...
                            'HorizontalAlignment','center',...
                            'ButtonSize', [100 20] ); 
                        
uicontrol( 'Parent', buttonbox,...
            'Style','radiobutton',...
            'Value',1,...
            'String','Batch',...
            'Tag','BatchRadioButton');
uicontrol( 'Parent', buttonbox,...
            'Style','radiobutton',...
            'Value',0,...
            'String','Simulation',...
            'Tag','SimulationRadioButton');

% File Panel
% + Tree
CheckboxTree('Parent', file_panel,...
            'Editable',false, 'DndEnabled',false,...
            'Tag','tree','RootVisible',false); 
        
% Process Panel
% + Grid, VBox
grid_process = uix.Grid( 'Parent', process_panel, 'Spacing', 0 ); 
box_process = uix.VBox( 'Parent', grid_process,'Padding',2,'Spacing',2,...
                        'Tag', 'box_process');

% + TabGroup
uitabgroup(box_process,'Position',[0 0 1 1],'Tag','tab');

% set heights    
box.Heights = [-1.5 -5 -7 -7 -1];
end
